### ISSUE TITLE
Orientation changes sign based on time

### ISSUE THREAD

**Issue by MD-MD** [CCNYRoboticsLab/imu_tools#14] opened 2013-07-22 02:01 UTC
I am having a strange problem when using the filter.  When I do "rosrun imu_filter_madgwick imu_filter_node" everything seems to work fine except that the signs of the orientations switch about every second.  At first I thought that it was every second _on the second_ but it is not, as you can see below.  This is the output from rostopic echo /imu/data using a Phidget Spatial 3/3/3 at the moment the switch occurs.  The important part to look at is the orientation; I did not move the imu at all and I certainly did not flip it about every axis in a fraction of a second.

header: 
  seq: 651
  stamp: 
    secs: 1374457284
    nsecs: 922849322
  frame_id: odom
orientation: 
  x: 0.0629537322659
  y: -0.10274833374
  z: 0.444023642596
  w: 0.885972732823
orientation_covariance: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
angular_velocity: 
  x: 0.000351509311352
  y: -0.00105452793405
  z: -0.00152245070651
angular_velocity_covariance: [1.2184696791468346e-07, 0.0, 0.0, 0.0, 1.2184696791468346e-07, 0.0, 0.0, 0.0, 1.2184696791468346e-07]
linear_acceleration: 
  x: 0.134691305761
  y: 0.0928026039696
  z: 9.67216991372
## linear_acceleration_covariance: [8.66124974095918e-06, 0.0, 0.0, 0.0, 8.66124974095918e-06, 0.0, 0.0, 0.0, 8.66124974095918e-06]

header: 
  seq: 652
  stamp: 
    secs: 1374457284
    nsecs: 930849322
  frame_id: odom
orientation: 
  x: -0.0625505324731
  y: 0.102060354997
  z: -0.444059882587
  w: -0.886064103676
orientation_covariance: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
angular_velocity: 
  x: -0.00316375833509
  y: 0.000703018622703
  z: -0.000936892742471
angular_velocity_covariance: [1.2184696791468346e-07, 0.0, 0.0, 0.0, 1.2184696791468346e-07, 0.0, 0.0, 0.0, 1.2184696791468346e-07]
linear_acceleration: 
  x: 0.1239003053
  y: 0.0868185037136
  z: 9.66804971354
linear_acceleration_covariance: [8.66124974095918e-06, 0.0, 0.0, 0.0, 8.66124974095918e-06, 0.0, 0.0, 0.0, 8.66124974095918e-06]

If anyone could identify what is causing this I would very much appreciate it, and I would be happy to post any additional information that may be needed.  Thanks!

**Comment by mintar** [comment] 2013-07-23 14:45
Hmm, that's weird, I've never seen this (I have a Phidgets Spatial 3/3/3 1044). Could you record a rosbag of the topics `/imu/data` and `/imu/data_raw` and upload it somewhere? This would be great. Also, what versions (SHA IDs) of `imu_tools` and `phidgets_drivers` are you using? (`git log | head -n 1`)

**Comment by MD-MD** [comment] 2013-07-24 19:12
We are using exactly the same Phidget.  I'll post a bag as soon as I have the chance to make one.  I also noticed that if you try to view it in rviz, either with rviz_imu_plugin (which we could only get compiled on one computer) or by watching the topic on rviz_plugin_tutorials the vector arrow behaved exactly as it should and did not flip around even though the sign was changing when we "rostopic echo"ed the output.

**Comment by MD-MD** [comment] 2013-07-24 19:49
phidgets_drivers : commit fb43a36a374fd9a1da100d5212974b58d11665b5
I don't seem to have the imu_tools git file.  Not sure how that is possible but if I do find it I'll add it.

**Comment by mintar** [comment] 2013-07-26 12:23
I've just checked, and I don't have this problem; so if you could upload a bag and post the version of `imu_tools` (and maybe the exact commands to reproduce your problem), that would be great.

**Comment by MD-MD** [comment] 2013-07-27 03:48
I found the imu_tools commit 7257d1d07fed4d0cb5e280e9cee3f31b7ce40937
This is a Google Drive link to the bag file I made https://docs.google.com/file/d/0B7WwcVi9Ubd5OTZEaml1VkxrYjQ/edit?usp=sharing
It records /imu/data_raw and /imu/data
We left the Phidget approximately level for a while, then rotated it.  The sign switching occurred throughout.

**Comment by mintar** [comment] 2013-07-29 13:36
Hmm. Something really weird is going on.

I've analyzed your bag file today, and can confirm that it shows the bug you described. Here's a plot (made using `rqt_plot`) from the start of your bag file, when the IMU is stationary:

![your-data-stationary](https://f.cloud.github.com/assets/320188/871728/b3bec5b6-f852-11e2-8d50-24d231e55762.png)

And here is a plot from near the end, when the IMU starts moving:

![your-data-moving](https://f.cloud.github.com/assets/320188/871730/c8d0d94e-f852-11e2-94a4-0c429ad4357d.png)

Clearly all the signs switch at about 1 Hz, as you described.

So what I did is I tried to reproduce the bug. First, I've filtered your bag file so I only have the raw input data from the IMU:

```
rosbag filter imufilterbag_2013-07-26-23-39-48.bag imufilterbag_2013-07-26-23-39-48-only-raw.bag 'topic == "/imu/data_raw"'
```

Next, I've only started the `imu_filter_madgwick` using the following launch file:

```
<launch>
  <node pkg="nodelet" type="nodelet" name="imu_manager"
    args="manager" output="screen" />

  <node pkg="nodelet" type="nodelet" name="ImuFilterNodelet"
    args="load imu_filter_madgwick/ImuFilterNodelet imu_manager"
    output="screen">

    # don't use mag! (causes IMU to drag behind after fast turns)
    <param name="use_mag" value="false"/>
  </node>
</launch>
```

I've plotted the same things again, but couldn't reproduce the bug:

![my-data-moving](https://f.cloud.github.com/assets/320188/871761/8654f428-f853-11e2-9eb2-2fa6b0f29861.png)

Now I'm stumped. Can you try to give detailed instructions on how to reproduce the bug from your bag file?

**Comment by MD-MD** [comment] 2013-07-29 14:42
I won't have access to my computer for a few days, but I can tell you this:  we did not use the launch file but rather started both nodes (NOT nodelettes) directly with rosrun

**Comment by mintar** [comment] 2013-07-29 15:07
Running the `imu_filter` node instead of the nodelet still didn't reproduce the bug for me.

I'm still eager to find this bug, so if you can send me those instructions when you get back to your PC, I promise I'll try fixing it.

**Comment by mintar** [comment] 2013-09-12 14:25
@MD-MD Any news on this? Since I can't reproduce the bug, I don't think it's a bug in imu_tools.

**Comment by mintar** [comment] 2013-11-12 14:01
Could not reproduce, so closing this issue as invalid.

**Closed as completed by mintar** 2013-11-12 14:01 UTC
Labels: bug, invalid
